### ISSUE TITLE
Is the fingerprint supposed to change, when https://www.thumbmarkjs.com/ is shown on a Firefox private window?

### ISSUE THREAD

**Issue by kiamlaluno** [ilkkapeltola/thumbmarkjs#11]
I visited https://www.thumbmarkjs.com/ using Firefox 122 running on Fedora 39. When visit the site from a private window, I get a different fingerprint. The difference is caused by the different value for `canvas.commonImageDataHash`.

Is this expected?

**Comment by ilkkapeltola** [comment]
It might be tough to 'fix'. Not intended, of course, but could be a 'by-design' kind of a thing.

I'll look into this at some point, but I suspect that Firefox does something funky with the canvas that is different between normal and private window. It could be potentially impossible to make these match (depends on what is going on), and the solution would be to disable canvas on Firefox. This can be done, but it then removes a quite powerful fingerprinting technique. Luckily, webgl seems to be intact, and audio.

**Comment by ilkkapeltola** [comment]
Okay decided to make a quick fix by removing canvas from Firefox in 0.12.2.

I'll probably need to add an option that people can choose between better persistence and higher granularity. For now, this is fine.

Thanks for pointing this out!

**Comment by kiamlaluno** [comment]
I also tried adding an exception for the site on the *Enhanced Tracking Protection* settings, but the fingerprints are still different. I also cleared the cache before visiting the site (after closing all the Firefox windows).
Apparently, Firefox randomizes some data in the private window. In fact, I get a different fingerprint all the times.

Thank you for your reply and for taking a look!

**Comment by ilkkapeltola** [comment]
Yeah, I've noticed this pattern as well. Throughout the same session, it stays the same, so you can't even calculate it multiple times and check for common bytes. It's probably impossible to fix in any other way, but for now, Firefox will not use canvas and rely on the other components only. Not great, but at least it's _a_ fix.
