### ISSUE TITLE
Edge gets detected as Chrome? 

### ISSUE THREAD

**Issue by danielkoller** [ilkkapeltola/thumbmarkjs#13]
Hi @ilkkapeltola, I noticed that Edge gets detected as Chrome. Is this wanted behaviour as they are both chromium based browsers? Thanks! 

![Bildschirmfoto 2024-01-30 um 10 20 56](https://github.com/ilkkapeltola/thumbmarkjs/assets/15102417/ee763526-ff6e-46d8-8113-ada37d5a938b)

**Comment by ilkkapeltola** [comment]
This is fixed now with 0.12.3. Thank you for reporting the issue!
