### ISSUE TITLE
adding applePay and memory heap

### ISSUE THREAD

**Issue by eran-barkai** [ilkkapeltola/thumbmarkjs#16]
display-mode: browser

**Comment by ilkkapeltola** [comment]
You're absolutely correct about this.
I've taken this out from v0.12.6 and published a new version.
Thanks for pointing it out!

**Comment by eran-barkai** [comment]
you seems receptive so as i was browsing on several of this solutions online (+ trying to make my own)
i think you should add:
* applePay
* memory heap

**Comment by ilkkapeltola** [comment]
Cool, yeah I'll look into these. Seem pretty straight forward.

**Comment by eran-barkai** [comment]
hi @ilkkapeltola, you are right with applePay, i saw it in both fingerprintjs and OP-Fingerprinting-script. i didn't see they used the payment method but this could be cool if stable or semi-stable.
[jsHeapSizeLimit](https://github.com/Joe12387/OP-Fingerprinting-Script/) i saw only here, they use jsHeapSizeLimit and it seems to be stable.

**Comment by ilkkapeltola** [comment]
Are you using this library: [OP-Fingerprinting-Script](https://github.com/Joe12387/OP-Fingerprinting-Script/tree/main) ?

By the looks of what's being done, I have concerns that the fingerprint is unstable. Maybe I'm wrong, but it feels like the use of performance alone is quite dangerous.  🤔

**Comment by eran-barkai** [comment]
Getting the results and fingerprint server side. Didn't check what stable and what not yet

**Comment by ilkkapeltola** [comment]
Actually, I have done some more testing on the jsHeapSizeLimit and I think you're right, it is very stable. I thought I had different values in incognito, but it was actually because I opened a file locally. That's not a concern for me, so yeah I'll implement that. If there are some issues in the field, it can be taken out later.

**Comment by ilkkapeltola** [comment]
Added support for these two in v0.13.0
