### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by danielkoller** [ilkkapeltola/thumbmarkjs#19]
Hi, 

it's me again. I currently experience this error, when trying to use Thumbmark.js in my Next.js project. 

![Bildschirmfoto 2024-02-07 um 11 08 24](https://github.com/ilkkapeltola/thumbmarkjs/assets/15102417/5289bdc2-e7b0-4b6a-8c3f-0d538d7c0478)

**Comment by ilkkapeltola** [comment]
This would suggest that the server-side script is trying to access the document, which doesn't work.

Are you calling the getFingerprint() function inside a UseEffect?
Or does this happen already at importing?

**Comment by ilkkapeltola** [comment]
So the issue is that, the Fingerprint library needs to have access to the document.
When the library gets called server-side, it doesn't.
When utilizing this in a Next.js project, the Fingerprint function needs to be called on page load, not when it's rendered server-side.

I was looking into Gatsby framework the other day and the way I got around this was by implementing the component like so:

```
import React, { useState, useEffect } from 'react';
import { getFingerprint } from "@thumbmarkjs/thumbmarkjs"

function Fingerprint() {
    const [fingerprint, setFingerprint] = useState('');
  
    useEffect(() => {
      getFingerprint()
        .then((result) => {
          setFingerprint(result);
        })
        .catch((error) => {
          console.error('Error getting fingerprint:', error);
        });
    }, []);
    
    return (
      <>{fingerprint}</>
    );
  }

export default Fingerprint
```

Not sure how well that fits into your project.

**Comment by danielkoller** [comment]
I was able to implement it in my Login Page like that -> 

`  useEffect(() => {
    import('@thumbmarkjs/thumbmarkjs').then(({ getFingerprint }) => {
      getFingerprint().then(setFingerprint).catch(console.error);
    });
  }, []);
`

Thanks for taking me into the right direction and sorry for opening up this ticket.

**Comment by ilkkapeltola** [comment]
No no, absolutely! I think I could improve on the documentation on this bit, since it seems to be a thing many people run into.
Oftentimes, Next.js doesn't really have components that rely on the document object, so it's probably not obvious how this one suddenly needs to be handled differently.

**Comment by ilkkapeltola** [comment]
@danielkoller could you provide a bit more elaborate code example of your implementation so that I can include that in my readme? I don't have a Next.js project and would rather skip setting one up if you'd be so kind to provide the example for me instead :D

**Comment by danielkoller** [comment]
Hej @ilkkapeltola, I implemented it like this. We collect both the fingerprint and also some additional data to store it in the database. It is working perfectly fine for us but the implementation might be a bit wonky. :D 

`  const [fingerprint, setFingerprint] = useState('');
  const [deviceDetails, setDeviceDetails] = useState({});

useEffect(() => {
    // eslint-disable-next-line import/no-extraneous-dependencies
    import('@thumbmarkjs/thumbmarkjs').then(
      ({ getFingerprint, getFingerprintData }) => {
        // eslint-disable-next-line no-console
        getFingerprint().then(setFingerprint).catch(console.error);
        getFingerprintData()
          .then((data) => {
            setDeviceDetails(data);
          })
          // eslint-disable-next-line no-console
          .catch(console.error);
      },
    );
  }, []);
`

We lastly have the whole object in our Next Auth Payload. 

Hope this helps. :)
