### ISSUE TITLE
ApplePaySession.supportsVersion goes up to 15, not 10

### ISSUE THREAD

**Issue by Joe12387** [ilkkapeltola/thumbmarkjs#20]
Hi there.

I noticed your ApplePaySession.supportsVersion implementation that was recently committed looks for versions only up to 10, then works its way down. However, Safari 17.3 currently returns true for values from 1 to 15, so it may be prudent to change your implementation to reflect this fact.

Thanks!

**Comment by ilkkapeltola** [comment]
Good point. I'll fix this right away!

**Comment by ilkkapeltola** [comment]
Done now in v0.13.2
