### ISSUE TITLE
importing in Typescript does not work

### ISSUE THREAD

**Issue by ilkkapeltola** [ilkkapeltola/thumbmarkjs#4]
allow importing in Typescript like

```
import { getFingerprint } from 'thumbmarkjs'
```

**Comment by ilkkapeltola** [comment]
@noe this should now work. The package is published in npm as `thumbmarkjs` and can be imported into a typescript project.
The version is 0.11.3-rc1. I'd appreciate if you can confirm it works for your use case and I'll release a final version after that.

I'll add more comments around this later, but the functions that are currently exposed are `getFingerprint`, `getVersion` and `getFingerprintData`

**Comment by noe** [comment]
I confirm it works.

However, it seems that, when the package is imported, `navigator` is used. This is an inconvenience for Next.js projects, as that import may happen server-side, where `navigator` is not defined.

I worked around this problem by using a [dynamic import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import). It would be great to change this behaviour or add a warning in the readme to let Next.js users about it.

**Comment by ilkkapeltola** [comment]
I've started a discussion, since I don't fully understand 😁
https://github.com/ilkkapeltola/thumbmarkjs/discussions/5
